AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Cluster:
    Type: String
    Description: Name of Cluster to host services and tasks
  TargetGroup:
    Type: String
    Description: TargetGroup for internet traffic
  TargetGroup8080:
    Type: String
    Description: TargetGroup for Traefik traffic
  LogGroup:
    Type: String
    Description: LogGroup to capture container output

  SecurityGroupWeb:
    Type: String
    Description: SecurityGroup for internet traffic
  SubnetPrivateOne:
    Type: String
    Description: Subnet A in a VPC
  SubnetPrivateTwo:
    Type: String
    Description: Subnet B in a VPC

Resources:
  RoleTraefik:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-traefik
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecs:*
                  - ecs:ListClusters
                  - ecs:DescribeClusters
                  - ecs:ListTasks
                  - ecs:DescribeTasks
                  - ecs:DescribeContainerInstances
                  - ecs:DescribeTaskDefinition
                  - ec2:DescribeInstances
                Resource: "*"

  ServiceTraefik:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionTraefik
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SecurityGroupWeb
          Subnets:
            - !Ref SubnetPrivateOne
            - !Ref SubnetPrivateTwo
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: traefik
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
        - ContainerName: traefik
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup8080

  TaskDefinitionTraefik:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Image: andrewgryan/traefik-ecs:latest
          Environment:
            - Name: CLUSTER
              Value: !Ref Cluster
            - Name: AWS_REGION
              Value: !Ref AWS::Region
          Name: traefik
          Memory: 32
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
            - ContainerPort: 8080
              HostPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Ref AWS::StackName
      TaskRoleArn: !Ref RoleTraefik
